//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFvetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C102107602Book
    {
        public int ISBN { get; set; }
        public string Title { get; set; }
        public int Published { get; set; }
        public int AuthorID { get; set; }
        public string StudID { get; set; }
    
        public virtual C102107602Author C102107602Author { get; set; }
        public virtual C102107602Student C102107602Student { get; set; }
    }
}
