//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFvetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C7602Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C7602Owner()
        {
            this.C7602Pet = new HashSet<C7602Pet>();
        }
    
        public int OwnerID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public int Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C7602Pet> C7602Pet { get; set; }
    }
}
