//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFvetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C7602Treatment
    {
        public System.DateTime Date { get; set; }
        public int ProcedureID { get; set; }
        public string PetName { get; set; }
        public int OwnerID { get; set; }
        public decimal PricePaid { get; set; }
        public string Notes { get; set; }
    
        public virtual C7602Pet C7602Pet { get; set; }
        public virtual C7602Procedure C7602Procedure { get; set; }
    }
}
